[DOCKER] Support HTTPS as well by making SFTP optional
aerius/database-build pull request #27
Opened 2023-11-30 12:27 UTC by SerhatG

We also want people to specify in their project settings whether they want to use SFTP or HTTPS.

2023-11-30 12:38 UTC, BertScholten requested changes

2023-11-30 12:38 UTC, BertScholten commented on docker/build-database.sh
> +[[ -n "${SFTP_READONLY_PASSWORD}" ]] && echo "\$sftp_data_readonly_password = '${SFTP_READONLY_PASSWORD}'" >> "${DBCONFIG_PATH}/AeriusSettings.User.rb"
```suggestion
[[ -n "${SFTP_READONLY_PASSWORD}" ]] && echo "\$sftp_data_readonly_password = '${SFTP_READONLY_PASSWORD}'" >> "${DBCONFIG_PATH}/AeriusSettings.User.rb"
[[ -n "${HTTPS_PASSWORD}" ]] && echo "\$https_data_password = '${HTTPS_PASSWORD}'" >> "${DBCONFIG_PATH}/AeriusSettings.User.rb"
```
Not sure if this the correct way to go if both are present, but the https password should be treated similar to the sftp one.

2023-11-30 12:40 UTC, SerhatG commented on docker/build-database.sh
> +[[ -n "${SFTP_READONLY_PASSWORD}" ]] && echo "\$sftp_data_readonly_password = '${SFTP_READONLY_PASSWORD}'" >> "${DBCONFIG_PATH}/AeriusSettings.User.rb"
ah yeah, didn't think about adding the HTTPS credentials (yet).. Can do that directly..

2023-11-30 12:44 UTC, SerhatG commented
I took the liberty to add `username` as well, as we are going to use accounts per person instead of one generic account. (in case developers want to use this locally - even though I can technically provide it in the User settings one)

2023-12-01 11:01 UTC, BertScholten approved these changes
LGTM

2023-12-01 11:02 UTC, merged