Add database common modules
aerius/database-build pull request #30
Opened 2024-02-19 12:54 UTC by JacobusXIII

Introducing the `database common modules` which are (grouped) database functionalities required for a database build or just very handy. This is to prevent each repository from defining its own modules (copy). See [`common/README.md`](./common/README.md) for more information about the modules.
We decided to move the modules from the `setup`-  to the `system` schema. We also ditched the `ae_` function prefix and orde to make this all work we have modified the build script and made it a bit more robust.

2024-02-19 16:17 UTC, BertScholten requested changes

2024-02-19 16:17 UTC, BertScholten commented on common/src/main/sql/system_asserts.sql
Shouldn't this be part of essentials? They seem useful for unittests/validations at least.

2024-02-19 16:17 UTC, BertScholten commented on common/src/main/sql/toolbox/system.sql
how is this file used? It seems a bit weird to reference other modules from within a common module, and don't think any of the referenced imports exist?

2024-02-26 10:58 UTC, JacobusXIII commented on common/src/main/sql/toolbox/system.sql
With this file you can easily add all `system` modules.

2024-02-26 10:59 UTC, JacobusXIII commented on common/src/main/sql/system_asserts.sql
They are useful but not essential for a database build.

2024-02-26 11:00 UTC, JacobusXIII commented on common/src/main/sql/essentials/postgres.sql
> + * Once the constraint (in this case the primary key) has been set, in the future clustering can be done by using: CLUSTER databasname.
Fixed

2024-02-26 11:01 UTC, JacobusXIII commented on common/src/main/sql/essentials/postgres.sql
Renamed the file to `postgres-maintenance.sql`.

2024-02-26 11:03 UTC, JacobusXIII commented on common/src/data/sql/.gitkeep
The build-scripts throws an error if there is no common data folder. So that's why I added this folder.

Maybe it's better to change the build script.

2024-02-26 11:11 UTC, JacobusXIII commented on README.md
> +# database-build
Repo is lacking documentation.

Added a link to the common `README.md`.

2024-02-26 14:47 UTC, BertScholten commented on common/src/data/sql/.gitkeep
think that's more a question of how the project using this common section is configured? If you don't have the path defined in `$common_data_paths` for instance, I don't think the build script will complain?

2024-02-26 14:53 UTC, JacobusXIII commented on common/src/data/sql/.gitkeep
Without a `$common_data_paths` defined, the script will throw an error. This is indeed not desirable. I will fix this differently.

2024-02-26 14:53 UTC, BertScholten commented on common/src/main/sql/toolbox/system.sql
But `common/src/main/sql/toolbox/system.sql` references a file like `'db-essentials.sql'` for instance, but that is not added in this pR?

2024-02-26 14:54 UTC, JacobusXIII commented on common/src/main/sql/toolbox/system.sql
I fixed that a while ago.

2024-02-26 14:57 UTC, JacobusXIII commented on common/src/main/sql/toolbox/system.sql
Found the problem! I will remote this file. File is in the wrong folder en replaced by `all_system.sql`.

2024-02-26 15:45 UTC, JacobusXIII commented on common/src/data/sql/.gitkeep
Removed the not empty check in the `Globals.rb`.

2024-04-17 08:14 UTC, BertScholten approved these changes
Few small comment suggestions, but LGTM

2024-04-17 08:14 UTC, BertScholten commented on common/README.md
> +The extended validation functionality. If you want to implement validations you will need this modules as well.
```suggestion
The extended validation functionality. If you want to implement validations you will need this module as well.
```

2024-04-17 08:14 UTC, BertScholten commented on common/src/main/sql/database-build/essentials/summaries.sql
> + * Function could generating files with statistics.
```suggestion
 * Function can generate files with statistics.
```

2024-04-30 11:28 UTC, SerhatG approved these changes

2024-09-03 07:02 UTC, SerhatG approved these changes

2024-09-04 10:32 UTC, merged